
-- Agregar AUTO_INCREMENT a claves primarias (excepto Usuario)

ALTER TABLE Contacto MODIFY cod INT NOT NULL AUTO_INCREMENT;

ALTER TABLE Enfermedad MODIFY cod INT NOT NULL AUTO_INCREMENT;

ALTER TABLE Medicacion MODIFY cod INT NOT NULL AUTO_INCREMENT;

ALTER TABLE Tratamiento MODIFY cod INT NOT NULL AUTO_INCREMENT;

ALTER TABLE Emergencias MODIFY cod INT NOT NULL AUTO_INCREMENT;

ALTER TABLE UsuarioEmergencias MODIFY cod INT NOT NULL AUTO_INCREMENT;

ALTER TABLE UsuarioTratamiento MODIFY cod INT NOT NULL AUTO_INCREMENT;

ALTER TABLE UsuarioMedicacion MODIFY cod INT NOT NULL AUTO_INCREMENT;

ALTER TABLE UsuarioEnfermedad MODIFY cod INT NOT NULL AUTO_INCREMENT;
